---
title: "lme-r"
format: html
editor: visual
---

## Dependencies

```{r}
# data wrangling
library(tidyverse)
# data utilities
library(timetk)
# estimating mixed effects models
library(lme4)
library(merTools)
library(glmmTMB)
library(nlme)
# correlograms
library(ggcorrplot)
library(corrplot)
# data visualisation
library(viridis)
library(ggthemes)
library(ggpubr)
library(zoo)
library(showtext)
library(patchwork)
library(ggrepel)
# display regression equation
library(equatiomatic)
# standardise input variables
  #library(arm)
  # reporting regression results
library(broom.mixed)
library(gtsummary)
library(sjPlot)
library(mgcv)
```

## Data import

```{r}
# Set working directory
wd <- '/your/path/to/working/directory/'
wd <- '/Users/carmen/Library/CloudStorage/OneDrive-TheUniversityofLiverpool/research/latin-mobility-covid'

# Set the country
country <- 'Chile'

# Initialize variables for country_short and country_code
country_short <- ""
country_code <- ""

# Assign country_short and country_code based on the country
if (country == 'Argentina') {
    country_short <- 'ARG'
    country_code <- 'AR'
} else if (country == 'Chile') {
    country_short <- 'CHL'
    country_code <- 'CL'
} else if (country == 'Colombia') {
    country_short <- 'COL'
    country_code <- 'CO'
} 
```

```{r}
category <- "density"
capital <- FALSE

if (capital == TRUE) {
  place <- 'capital'
} else {
  place <- 'fuas'
}
```

```{r}
capital
# Read the CSV file
file_path <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/trend_', place, '.csv')
df <- read.csv(file_path)

df$time2 <- df$time^2
```

```{r}
dates <- read.csv(paste0(wd, '/data/outputs/', country_short, '/mov-analysis/dates.csv'))

df_stringency <- read.csv(paste0(wd, '/data/inputs/covid-stringency/owid-covid-data.csv')) %>%
  filter(location == "Argentina") %>% 
  filter(date %in% dates$date) %>% 
  slice(seq(1, n(), by = 7)) %>% 
  mutate(time = seq(0, n() - 1)) %>%
  select(time, stringency_index)

df <- df %>% left_join(df_stringency, by = "time")

df <- df[, !(names(df) == "X")]

```

## Define models

```{r}

eq1 <- y ~ time
m1 <- glmmTMB(eq1, data = df)

###

eq1s <- y ~ time + stringency_index
m1s <- glmmTMB(eq1s, data = df)

###

eq2cat <- y ~ time + cat
m2cat <- glmmTMB(eq2cat, data = df)

eq2cats <- y ~ time + cat + stringency_index
m2cats <- glmmTMB(eq2cats, data = df)

###

eq3cat <- y ~ time + (1|cat)
m3cat <- glmmTMB(eq3cat, data = df)
m3cat_re <- plot_model(m3cat, type ="re")

eq3cats <- y ~ time + (1|cat) + stringency_index
m3cats <- glmmTMB(eq3cats, data = df)
m3cats_re <- plot_model(m3cats, type ="re")

###

df$catf <- factor(df$cat)
eq4cat <- y ~ time + (0 + time|catf) 
m4cat <- glmmTMB(eq4cat, data = df)
m4cat_re <- plot_model(m4cat, type ="re")

df$catf <- factor(df$cat)
eq4cats <- y ~ time + (0 + time|catf) + stringency_index
m4cats <- glmmTMB(eq4cats, data = df)
m4cats_re <- plot_model(m4cats, type ="re")

###

df$catf <- factor(df$cat)
eq5cat <- y ~ time + (time|catf) 
m5cat <- glmmTMB(eq5cat, data = df)
m5cat_re <- plot_model(m5cat, type ="re")

df$catf <- factor(df$cat)
eq5cats <- y ~ time + (time|catf) + stringency_index
m5cats <- glmmTMB(eq5cats, data = df)
m5cats_re <- plot_model(m5cats, type ="re")

###

eq6cat <- y ~ time + time2 + (time|cat) 
m6cat <- glmmTMB(eq6cat, data = df)
m6cat_re <- plot_model(m6cat, type ="re")

eq6cats <- y ~ time + time2 + (time|cat) + stringency_index
m6cats <- glmmTMB(eq6cats, data = df)
m6cats_re <- plot_model(m6cats, type ="re")

###

eq7cat <- y ~ time + time2 + (time + time2 | cat)
m7cat <- glmmTMB(eq7cat, data = df)
m7cat_re <- plot_model(m7cat, type ="re")

eq7cats <- y ~ time + time2 + (time + time2|cat) + stringency_index
m7cats <- glmmTMB(eq7cats, data = df)
m7cats_re <- plot_model(m7cats, type ="re")

###

df$cat  <- factor(df$cat)
eq8cat <- y ~ 
    s(time, k = 8) + 
    s(time, cat, bs = "fs", k = 7)
m_gam <- gam(eq8cat, data = df, method = "REML")

df$cat  <- factor(df$cat)
eq8cats <- y ~ 
    s(time, k = 8) + 
    stringency_index + 
    s(time, cat, bs = "fs", k = 7)
m_gams <- gam(eq8cats, data   = df, method = "REML")

```

## Save model data

```{r}
models_cat <- list(
  m1,
  m2cat,
  m3cat,
  m4cat,
  m5cat,
  m6cat,
  m7cat, 
  m_gam
  )
tidy_fixed <- map_df(models_cat, ~ tidy(.x, parametric = TRUE), .id = "model")
tidy_smooth <- map_df(models_cat, ~ tidy(.x, smooth = TRUE), .id = "model")
tidy_results_cat <- bind_rows(tidy_fixed, tidy_smooth) %>%
  distinct()
file_tidy_results_cat <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_netflows_', place, '_param_tidy_results_cat_new.csv')
# write.csv(tidy_results_cat, file_tidy_results_cat, row.names = FALSE)

glance_results_cat <- map_df(models_cat, glance, .id = "model")
file_glance_results_cat <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_netflows_', place, '_param_glance_results_cat_new.csv')
# write.csv(glance_results_cat, file_glance_results_cat, row.names = FALSE)

models_cats <- list(
  m1s,
  m2cats,
  m3cats,
  m4cats,
  m5cats,
  m6cats,
  m7cats,
  m_gams
  )
tidy_fixed <- map_df(models_cats, ~ tidy(.x, parametric = TRUE), .id = "model")
tidy_smooth <- map_df(models_cats, ~ tidy(.x, smooth = TRUE), .id = "model")
tidy_results_cats <- bind_rows(tidy_fixed, tidy_smooth) %>%
  distinct()

file_tidy_results_cats <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_netflows_', place, '_param_tidy_results_cats_new.csv')
# write.csv(tidy_results_cats, file_tidy_results_cats, row.names = FALSE)

glance_results_cats <- map_df(models_cats, glance, .id = "model")
file_glance_results_cats <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_netflows_', place, '_param_glance_results_cats_new.csv')
# write.csv(glance_results_cats, file_glance_results_cats, row.names = FALSE)
```

## Save random effects data

```{r}

file_m3cat_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m3cat_re_new.csv')
# write.csv(m3cat_re[[1]], file_m3cat_re, row.names = FALSE)

file_m3cats_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m3cats_re_new.csv')
# write.csv(m3cats_re[[1]], file_m3cats_re, row.names = FALSE)

###

file_m4cat_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m4cat_re_new.csv')
# write.csv(m4cat_re[[1]], file_m4cat_re, row.names = FALSE)

file_m4cats_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m4cats_re_new.csv')
# write.csv(m4cats_re[[1]], file_m4cats_re, row.names = FALSE)

###

file_m5cat_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m5cat_re_new.csv')
# write.csv(m5cat_re[[1]], file_m5cat_re, row.names = FALSE)

file_m5cats_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m5cats_re_new.csv')
# write.csv(m5cats_re[[1]], file_m5cats_re, row.names = FALSE)

###

file_m6cat_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m6cat_re_new.csv')
# write.csv(m6cat_re[[1]], file_m6cat_re, row.names = FALSE)

file_m6cats_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m6cats_re_new.csv')
# write.csv(m6cats_re[[1]], file_m6cats_re, row.names = FALSE)

###

file_m7cat_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m7cat_re_new.csv')
# write.csv(m7cat_re[[1]], file_m7cat_re, row.names = FALSE)

file_m7cats_re <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/data_trend_param_', place, '_m7cats_re_new.csv')
# write.csv(m7cats_re[[1]], file_m7cats_re, row.names = FALSE)

```

## Other

```{r}
# p1_m1me <- plot_model(m3o_re, terms = c("1", "time")) %>% 
#   .$data %>% ggplot(aes(x=estimate, y=term, color=group)) +
#   geom_point(size = 3.5,  colour = "black") +
#   geom_errorbar(aes(xmin = conf.low, xmax = conf.high), 
#                 width=.05, color= "black") +
#   geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
#   scale_color_manual(values=c("#88ccee")) +
#   theme(legend.position = "none",
#         axis.title.y = element_blank(),
#         axis.text = element_text(size = 10.5)
#   ) +
#   scale_y_discrete(labels=c("time" = "Week", 
#                             "1" = "Intercept")) +
#   geom_vline(xintercept=0, 
#              linetype="solid", 
#              color = "grey20",
#              linewidth=1,
#              alpha =.2) +
#   labs(title = "Main fixed effects")
# 
# p1_m1me
```

```{r}
# m2_re <- plot_model(m,
#            type ="re", terms = "O")
# 
# m2_re <- m2_re[[1]]$data
# 
# p2_m2re <- m2_re %>% filter(facet == "O (Intercept)") %>% 
#   ggplot(aes(x=estimate, y=term, color=group)) +
#   geom_point(size = 3.5,  colour = "black") +
#   geom_errorbar(aes(xmin = conf.low, xmax = conf.high), 
#                 width=.8, color= "black") +
#   geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
#   scale_color_manual(values=c("#ddcc77", "#88ccee")) +
#   theme(legend.position = "none",
#         axis.title.y = element_blank(),
#         axis.text = element_text(size = 10.5)
#         ) +
#   geom_vline(xintercept=0, 
#              linetype="solid", 
#              color = "grey20",
#              size=1,
#              alpha =.2) +
#   labs(title = "d")
# 
# p2_m2re
```

```{r}
# eq <- y ~  time + (time | O) + (time | D)
# model <- glmmTMB(eq, data = df)
```

```{r}
# pm3o <- plot_model(m3o, terms = c("time", "O")) %>% 
#   .$df %>% ggplot(aes(x=estimate, y=term, color=group)) +
#   geom_point(size = 3.5,  colour = "black") +
#   geom_errorbar(aes(xmin = conf.low, xmax = conf.high), 
#                 width=.05, color= "black") +
#   geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
#   scale_color_manual(values=c("#88ccee")) +
#   theme(legend.position = "none",
#         axis.title.y = element_blank(),
#         axis.text = element_text(size = 10.5)
#   ) +
#   scale_y_discrete(labels=c("z_stringency_index" = "Stringency t", 
#                             "z_cases" = "New cases t",
#                             "lag(z_stringency_index, 1)" = "Stringency t-1")) +
#   geom_vline(xintercept=0, 
#              linetype="solid", 
#              color = "grey20",
#              linewidth=1,
#              alpha =.2) +
#   labs(title = "c",
#        subtitle = " Main fixed effects")
# 
# p1_m
```

## Plots of RE

```{r}
m3cat_re
m3cats_re
m4cat_re
m4cats_re
m5cat_re
m5cats_re
m6cat_re
m6cats_re
m7cat_re
m7cats_re
```

```{r}
m6cat_re[[1]]$estimate[[6]]

m6cat$fit$par
```

```{r}
# Create predicted data frame for time 1 to 1000
pred_df_1 <- tibble(time = 1:300, time2 = time^2,
  fitted = (m6cat$fit$par[[1]] + m6cat_re[[1]]$estimate[[1]]) +
    (m6cat$fit$par[[2]] + m6cat_re[[1]]$estimate[[6]]) * time + 
    m6cat$fit$par[[3]] * time2)

# Create predicted data frame for time 1 to 1000
pred_df_2 <- tibble(time = 1:300, time2 = time^2,
  fitted = (m6cat$fit$par[[1]] + m6cat_re[[1]]$estimate[[2]]) +
    (m6cat$fit$par[[2]] + m6cat_re[[1]]$estimate[[7]]) * time + 
    m6cat$fit$par[[3]] * time2)

# Create predicted data frame for time 1 to 1000
pred_df_3 <- tibble(time = 1:300, time2 = time^2,
  fitted = (m6cat$fit$par[[1]] + m6cat_re[[1]]$estimate[[3]]) +
    (m6cat$fit$par[[2]] + m6cat_re[[1]]$estimate[[8]]) * time + 
    m6cat$fit$par[[3]] * time2)

# Create predicted data frame for time 1 to 1000
pred_df_4 <- tibble(time = 1:300, time2 = time^2,
  fitted = (m6cat$fit$par[[1]] + m6cat_re[[1]]$estimate[[4]]) +
    (m6cat$fit$par[[2]] + m6cat_re[[1]]$estimate[[9]]) * time + 
    m6cat$fit$par[[3]] * time2)

# Create predicted data frame for time 1 to 1000
pred_df_5 <- tibble(time = 1:300, time2 = time^2,
  fitted = (m6cat$fit$par[[1]] + m6cat_re[[1]]$estimate[[5]]) +
    (m6cat$fit$par[[2]] + m6cat_re[[1]]$estimate[[10]]) * time + 
    m6cat$fit$par[[3]] * time2)



```

## Compute recovery times for spline model. The 95% confidence intervals are computed via bootstrap.

```{r}
stringency <- FALSE
```

```{r}
# Create new time sequence covering the range of your original data
new_time <- expand.grid(
  time = seq(min(df$time), max(df$time)*100, length.out = max(df$time)*100-min(df$time)+1),
  cat = levels(df$cat)   # one dataset per group
)

new_time <- new_time %>%
  left_join(df[, c("time", "cat", "stringency_index")], by = c("time", "cat"))

new_time$stringency_index[is.na(new_time$stringency_index)] <- 0


if (stringency == FALSE) {
  new_time <- expand.grid(
  time = seq(min(df$time), max(df$time)*100, length.out = max(df$time)*100-min(df$time)+1),
  cat = levels(df$cat)   # one dataset per group
)
  pred_base <- predict(m_gam, newdata = new_time, se.fit = TRUE)
} else {
  pred_base <- predict(m_gams, newdata = new_time, se.fit = TRUE)
}

new_time$fit <- pred_base$fit
new_time$se  <- pred_base$se.fit

# Find FIRST root where preds(t) == target
get_root_threshold <- function(time, preds, target) {
  diff_sign <- diff(sign(preds - target))
  crossings <- which(diff_sign != 0)
  if (length(crossings) == 0) return(NA)
  
  i <- crossings[1]  # first crossing
  out <- tryCatch(
    uniroot(function(t) {
      approx(time, preds - target, xout = t)$y
    },
    lower = time[i],
    upper = time[i + 1])$root,
    error = function(e) NA
  )
  return(out)
}

alphas <- seq(0, 1, by = 0.05)   # adjust resolution as needed

# Bootstrap confidence intervals
set.seed(123)
n_boot <- 200   # increase to 500–1000 for publication

results_alpha <- map_df(levels(df$cat), function(g) {
  
  group_data <- new_time %>% filter(cat == g)

  # group-specific y(t=0): use earliest time in grid for that group
  idx0 <- which.min(group_data$time)
  y0_group <- group_data$fit[idx0]
  
  # For each alpha / target, bootstrap
  map_df(seq_along(alphas), function(j) {
    alpha   <- alphas[j]
    target <- (1 - alpha) * y0_group
    
    boot_roots <- replicate(n_boot, {
      # simulate one curve from uncertainty
      y_sim <- rnorm(nrow(group_data), mean = group_data$fit, sd = group_data$se)
      get_root_threshold(group_data$time, y_sim, target)
    })
    
    data.frame(
      cat        = g,
      alpha    = alpha,
      y_target = target,
      t_alpha  = median(boot_roots, na.rm = TRUE),
      CI_lower = quantile(boot_roots, 0.025, na.rm = TRUE),
      CI_upper = quantile(boot_roots, 0.975, na.rm = TRUE),
      SD_t_alpha = sd(boot_roots, na.rm = TRUE)
    )
  })
})

results_alpha <- as_tibble(results_alpha)  

```

## Save recovery times for splines model

```{r}

if (stringency == FALSE) {
  if (capital == TRUE) {
    file_results_alpha <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/recovery-times-capital-gam-r1.csv')
  } else {
    file_results_alpha <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/recovery-times-fuas-gam-r1.csv')
  }
} else {
  if (capital == TRUE) {
    file_results_alpha <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/recovery-times-capital-gams-r1.csv')
  } else {
    file_results_alpha <- paste0(wd, '/data/outputs/', country_short, '/mov-analysis/by-', category, '/recovery-times-fuas-gams-r1.csv')
  }
}
write.csv(results_alpha, file_results_alpha, row.names = FALSE)

```

## Plot recovery times splines model for various alpha

```{r}
ggplot(results_alpha, aes(x = alpha, y = t_alpha, color = cat, group = cat)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = CI_lower, ymax = CI_upper, fill = cat),
              alpha = 0.15, color = NA) +
  labs(
    title = "Time to reach threshold level (1 - α)",
    x = expression(alpha),
    y = expression(t(alpha)),
    color = "Group (cat)",
    fill = "Group (cat)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", size = 16)
  )

```
